version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_one
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql_one
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_osp
      MYSQL_USER: db_osp
      MYSQL_PASSWORD: db_osp
      MYSQL_ROOT_PASSWORD: db_osp
      MYSQL_ROOT_HOST: '%'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql  

  adminer:
    networks:
      - laravel
    image: adminer
    restart: always
    ports:
      - 8080:8080    

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_one
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_one_osp
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm_one_osp
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_one_osp
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_one_osp
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel

volumes:
  mysql_data: